# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 13:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voodoo_plans', '0002_activity_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itinerary',
            old_name='occasion',
            new_name='preference',
        ),
        migrations.RenameField(
            model_name='itinerary',
            old_name='party',
            new_name='purpose',
        ),
    ]
